import type { Metadata } from "next";
import  {Arimo}  from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";
import Footer from "./footer";

const arimo = Arimo({ subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Doctor Within Border",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={arimo.className}>
      <Navbar />
        {children}</body>
      <Footer />
    </html>
  );
}
